<?php

namespace AppBundle\Repository;

/**
 * ContadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContadorRepository extends \Doctrine\ORM\EntityRepository
{
}
