<?php

namespace AppBundle\Repository;

/**
 * TreinamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreinamentoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function findTreinos()
    {
        $em = $this->getEntityManager($limite = 3);
        $consulta = $em->createQuery('
                                SELECT t
                                FROM AppBundle:Treinamento t
                                ORDER BY t.data ASC
                                ');
        $consulta->setMaxResults($limite);
        return $consulta->getResult();
    }
}
