# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    upload_directory: '%kernel.root_dir%/../web/uploads'
    web_dir: '%kernel.root_dir%/../web'

services:
    app.upload_directory:
        class: AppBundle\Services\FileUploader
        arguments: ['%upload_directory%', '@doctrine.orm.entity_manager']

    app.form.type.upload:
        class: AppBundle\Form\UploadType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
        twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }
